let cards=[], topic='love', current=[];
const topicLabels={love:'♥ LOVE',career:'▣ CAREER',money:'◉ MONEY',general:'✦ GENERAL'};
async function init(){cards=await fetch('tarot.json').then(r=>r.json());setupNav();setupTopics();renderPreview();renderDeck();renderHistory();updateClock();setInterval(updateClock,1000);draw(false)}
function setupNav(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>show(b.dataset.view));document.querySelectorAll('[data-goto]').forEach(b=>b.onclick=()=>show(b.dataset.goto));startBtn.onclick=()=>{show('reading');draw(true)};drawBtn.onclick=()=>draw(true);saveBtn.onclick=saveHistory;shareBtn.onclick=shareResult;clearHistory.onclick=()=>{localStorage.removeItem('riverTarotHistory');renderHistory()}}
function show(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===id));if(id==='history')renderHistory();window.scrollTo({top:0,behavior:'smooth'})}
function setupTopics(){document.querySelectorAll('.topic').forEach(b=>b.onclick=()=>{topic=b.dataset.topic;document.querySelectorAll('.topic').forEach(x=>x.classList.toggle('active',x===b));topicBadge.textContent=topicLabels[topic]})}
function renderPreview(){let sample=[cards.find(c=>c.slug==='18-moon'),cards.find(c=>c.slug==='17-star'),cards.find(c=>c.slug==='09-hermit')];previewCards.innerHTML=sample.map(c=>`<img src="${c.image}" alt="${c.zh}">`).join('')}
function draw(revealView=true){if(!cards.length)return;let pool=[...cards],picked=[];for(let i=0;i<3;i++){let n=Math.floor(Math.random()*pool.length);let c=pool.splice(n,1)[0];picked.push({...c,orientation:Math.random()<.5?'upright':'reversed',revealed:false})}current=picked;renderSpread();detail.innerHTML='<h3>CARD READING</h3><p>點擊任一張牌翻開並查看牌義。</p>';summaryText.textContent='三張牌尚未全部揭曉。依序翻開「過去／現在／未來」。';status.textContent='';if(revealView)show('reading')}
function renderSpread(){const pos=[['PAST','WHAT YOU CARRY'],['PRESENT','WHAT IS HERE'],['FUTURE','WHAT COULD BE']];spread.innerHTML=current.map((c,i)=>`<div class="slot"><div class="card ${c.revealed?'revealed':''}" data-i="${i}"><div class="card-inner"><div class="card-face card-back"></div><div class="card-face card-front ${c.orientation==='reversed'?'reversed':''}"><img src="${c.image}" alt="${c.zh}"></div></div></div><h4>${pos[i][0]}</h4><small>${pos[i][1]}</small></div>`).join('');spread.querySelectorAll('.card').forEach(el=>el.onclick=()=>reveal(+el.dataset.i))}
function reveal(i){current[i].revealed=true;renderSpread();showDetail(i);if(current.every(c=>c.revealed))renderSummary()}
function showDetail(i){let c=current[i],o=c.orientation,key=topic;detail.innerHTML=`<h3>CARD READING</h3><img class="mini ${o==='reversed'?'rev':''}" src="${c.image}"><h2>${c.en}<br><small>${c.zh}</small></h2><div class="orientation">${o==='upright'?'UPRIGHT 正位':'REVERSED 逆位'}</div><h3>CORE MEANING</h3><p>${c.meanings[o].core}</p><h3>${topicLabels[key]} READING</h3><p>${c.meanings[o][key]}</p><h3>RIVER READING</h3><p>${c.river[o]}</p>`}
function renderSummary(){let p=current.map((c,i)=>`${['過去','現在','未來'][i]}：${c.zh}${c.orientation==='upright'?'正位':'逆位'} — ${c.meanings[c.orientation][topic]}`);summaryText.textContent=p.join('　');}
function saveHistory(){if(!current.length||!current.every(c=>c.revealed)){status.textContent='請先把三張牌全部翻開。';return}let h=JSON.parse(localStorage.getItem('riverTarotHistory')||'[]');h.unshift({time:new Date().toISOString(),topic,cards:current.map(c=>({id:c.id,orientation:c.orientation}))});h=h.slice(0,50);localStorage.setItem('riverTarotHistory',JSON.stringify(h));status.textContent='✓ Saved to history log.'}
function renderHistory(){if(!cards.length)return;let h=JSON.parse(localStorage.getItem('riverTarotHistory')||'[]');historyList.innerHTML=h.length?h.map(x=>`<div class="history-item"><strong>${new Date(x.time).toLocaleString('zh-TW')} · ${topicLabels[x.topic]}</strong><div class="history-cards">${x.cards.map(z=>{let c=cards.find(q=>q.id===z.id);return `<div class="history-card"><img class="${z.orientation==='reversed'?'rev':''}" src="${c.image}"><span>${c.zh} · ${z.orientation==='upright'?'正位':'逆位'}</span></div>`}).join('')}</div></div>`).join(''):'<p>尚無抽牌紀錄。</p>'}
async function shareResult(){if(!current.length||!current.every(c=>c.revealed)){status.textContent='請先把三張牌全部翻開。';return}let text=`RIVER TAROT · ${topicLabels[topic]}\n`+current.map((c,i)=>`${['過去','現在','未來'][i]}：${c.zh}（${c.orientation==='upright'?'正位':'逆位'}）`).join('\n');try{if(navigator.share)await navigator.share({title:'RIVER TAROT',text});else{await navigator.clipboard.writeText(text);status.textContent='✓ 結果已複製。'}}catch(e){status.textContent='分享已取消。'}}
function renderDeck(){if(!cards.length)return;deckGrid.innerHTML=cards.map(c=>`<figure><img loading="lazy" src="${c.image}"><figcaption>${c.zh}</figcaption></figure>`).join('')}
function updateClock(){let d=new Date();clock.textContent=d.toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit'})+' · '+d.toLocaleDateString('en-US',{year:'numeric',month:'short',day:'2-digit'})}
init();